name: prettier
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
