name: prettier
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: prettier --version
        with:
          args: --version
      - name: prettier --help
        with:
          args: --help
      - name: prettier --check .
        with:
          args: --check .
      - name: prettier --write .
        with:
          args: --write .
