name: prettier
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: actionsx/prettier
        uses: actionsx/prettier@v2
        with:
          args: --write **/*.js
